# Generated by Django 5.1.15 on 2026-05-06 12:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('is_headquarters', models.BooleanField(default=False, verbose_name='Siège social')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Code postal')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Région')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Agence',
                'verbose_name_plural': 'Agences',
                'ordering': ['-is_headquarters', 'city'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=20, unique=True, verbose_name='Référence')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('property_type', models.CharField(choices=[('APARTMENT', 'Appartement'), ('HOUSE', 'Maison'), ('LAND', 'Terrain'), ('COMMERCIAL', 'Local commercial'), ('OFFICE', 'Bureau'), ('BUILDING', 'Immeuble'), ('OTHER', 'Autre')], max_length=15, verbose_name='Type')),
                ('transaction_type', models.CharField(choices=[('SALE', 'Vente'), ('RENT', 'Location')], default='SALE', max_length=10, verbose_name='Transaction')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('AVAILABLE', 'Disponible'), ('UNDER_OFFER', 'Sous compromis'), ('SOLD', 'Vendu'), ('WITHDRAWN', 'Retiré')], default='DRAFT', max_length=15, verbose_name='Statut')),
                ('is_featured', models.BooleanField(default=False, verbose_name='À la une')),
                ('surface', models.PositiveIntegerField(verbose_name='Surface (m²)')),
                ('land_surface', models.PositiveIntegerField(blank=True, null=True, verbose_name='Surface terrain (m²)')),
                ('rooms', models.PositiveIntegerField(default=1, verbose_name='Nombre de pièces')),
                ('bedrooms', models.PositiveIntegerField(default=0, verbose_name='Chambres')),
                ('bathrooms', models.PositiveIntegerField(default=0, verbose_name='Salles de bain')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Étage')),
                ('has_garage', models.BooleanField(default=False, verbose_name='Garage')),
                ('has_garden', models.BooleanField(default=False, verbose_name='Jardin')),
                ('has_pool', models.BooleanField(default=False, verbose_name='Piscine')),
                ('has_balcony', models.BooleanField(default=False, verbose_name='Balcon/Terrasse')),
                ('has_elevator', models.BooleanField(default=False, verbose_name='Ascenseur')),
                ('is_furnished', models.BooleanField(default=False, verbose_name='Meublé')),
                ('energy_class', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=1, verbose_name='Classe énergétique')),
                ('construction_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Année de construction')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix (€)')),
                ('monthly_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Charges mensuelles (€)')),
                ('agency_fees_percent', models.DecimalField(decimal_places=2, default=Decimal('4.00'), max_digits=4, verbose_name="Frais d'agence (%)")),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Code postal')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Région')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.agency', verbose_name='Agence')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_properties', to=settings.AUTH_USER_MODEL, verbose_name='Agent référent')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties_for_sale', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': 'Bien',
                'verbose_name_plural': 'Biens',
                'ordering': ['-is_featured', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='properties.property')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='properties/%Y/%m/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('is_main', models.BooleanField(default=False, verbose_name='Photo principale')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='properties.property', verbose_name='Bien')),
            ],
            options={
                'verbose_name': 'Photo de bien',
                'verbose_name_plural': 'Photos de biens',
                'ordering': ['-is_main', 'order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'transaction_type'], name='properties__status_0c7a86_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city'], name='properties__city_74fa1a_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price'], name='properties__price_32e7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type'], name='properties__propert_5c7790_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favoriteproperty',
            unique_together={('user', 'property')},
        ),
    ]
