# Generated by Django 5.1.15 on 2026-05-06 12:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('question', models.TextField(verbose_name='Question')),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('response', models.TextField(blank=True, verbose_name='Réponse')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='info_requests', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_requests', to='properties.property')),
            ],
            options={
                'verbose_name': "Demande d'informations",
                'verbose_name_plural': "Demandes d'informations",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=20, unique=True, verbose_name='Référence')),
                ('type', models.CharField(choices=[('SALE', 'Vente'), ('RENT', 'Location')], default='SALE', max_length=10, verbose_name='Type')),
                ('status', models.CharField(choices=[('OFFER_MADE', 'Offre déposée'), ('OFFER_ACCEPTED', 'Offre acceptée'), ('COMPROMISE', 'Compromis signé'), ('FINANCING', 'Financement en cours'), ('SIGNED', 'Acte signé'), ('CANCELLED', 'Annulée')], default='OFFER_MADE', max_length=20, verbose_name='Statut')),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix proposé (€)')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix final (€)')),
                ('agency_commission', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Commission agence (€)')),
                ('offer_date', models.DateField(verbose_name='Date offre')),
                ('expected_signature_date', models.DateField(blank=True, null=True, verbose_name='Signature prévue')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Signé le')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Agent référent')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='Acheteur/Locataire')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='properties.property')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('visible_to_client', models.BooleanField(default=True, verbose_name='Visible client')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Étape de transaction',
                'verbose_name_plural': 'Étapes de transactions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('preferred_date', models.DateField(blank=True, null=True, verbose_name='Date souhaitée')),
                ('preferred_time', models.TimeField(blank=True, null=True, verbose_name='Heure souhaitée')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('DONE', 'Effectuée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=15, verbose_name='Statut')),
                ('confirmed_date', models.DateTimeField(blank=True, null=True, verbose_name='Date confirmée')),
                ('agent_notes', models.TextField(blank=True, verbose_name='Notes agent')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_requests', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to='properties.property', verbose_name='Bien')),
            ],
            options={
                'verbose_name': 'Demande de visite',
                'verbose_name_plural': 'Demandes de visite',
                'ordering': ['-created_at'],
            },
        ),
    ]
