# Generated by Django 5.1.15 on 2026-05-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.DateField(help_text='Premier jour du mois concerné')),
                ('city', models.CharField(max_length=100)),
                ('property_type', models.CharField(max_length=15)),
                ('transaction_type', models.CharField(max_length=10)),
                ('listings_count', models.PositiveIntegerField(default=0)),
                ('avg_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('median_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_price_per_sqm', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_surface', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sales_count', models.PositiveIntegerField(default=0)),
                ('avg_days_to_sell', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
            ],
            options={
                'verbose_name': 'Snapshot marché',
                'verbose_name_plural': 'Snapshots marché',
                'ordering': ['-period', 'city'],
                'unique_together': {('period', 'city', 'property_type', 'transaction_type')},
            },
        ),
    ]
